package tun

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/xtls/xray-core/common/errors"
)

const (
	autoRouteCleanupScriptPrefix = "xray-auto-route-cleanup-"
	autoRouteCleanupScriptSuffix = ".sh"
)

var (
	checkStaleAutoRouteCleanupScriptsOnce sync.Once
	staleAutoRouteCleanupScripts          []string
)

func checkStaleAutoRouteCleanupScripts(ctx context.Context) error {
	checkStaleAutoRouteCleanupScriptsOnce.Do(func() {
		staleAutoRouteCleanupScripts = listAutoRouteCleanupScripts()
	})
	if len(staleAutoRouteCleanupScripts) == 0 {
		return nil
	}
	for _, script := range staleAutoRouteCleanupScripts {
		errors.LogWarning(ctx, "[tun] found stale auto_route cleanup script ", script, "; run it before starting Xray: ", autoRouteCleanupCommand(script))
	}
	return errors.New("stale auto_route cleanup script exists; run the cleanup command before starting Xray")
}

func writeAutoRouteCleanupScript(ctx context.Context, tunName string, commands []string) (string, error) {
	if len(commands) == 0 {
		return "", nil
	}

	content := buildAutoRouteCleanupScript(commands)
	var lastErr error
	for _, dir := range autoRouteCleanupDirs() {
		if err := os.MkdirAll(dir, 0o700); err != nil {
			lastErr = err
			continue
		}
		_ = os.Chmod(dir, 0o700)

		path := filepath.Join(dir, autoRouteCleanupScriptName(tunName))
		file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o700)
		if err != nil {
			lastErr = err
			continue
		}
		_, writeErr := file.WriteString(content)
		closeErr := file.Close()
		if writeErr != nil || closeErr != nil {
			_ = os.Remove(path)
			if writeErr != nil {
				lastErr = writeErr
			} else {
				lastErr = closeErr
			}
			continue
		}

		errors.LogWarning(ctx, "[tun] auto_route cleanup script created at ", path, "; if Xray exits unexpectedly, run: ", autoRouteCleanupCommand(path))
		return path, nil
	}
	if lastErr == nil {
		lastErr = fmt.Errorf("no cleanup script directory is available")
	}
	return "", lastErr
}

func removeAutoRouteCleanupScript(ctx context.Context, path string) {
	if path == "" {
		return
	}
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		errors.LogWarningInner(ctx, err, "[tun] failed to remove auto_route cleanup script ", path, "; run manually if needed: ", autoRouteCleanupCommand(path))
	}
}

func logAutoRouteCleanupScript(ctx context.Context, path string) {
	if path == "" {
		return
	}
	errors.LogWarning(ctx, "[tun] auto_route cleanup may be incomplete; run manually if needed: ", autoRouteCleanupCommand(path))
}

func buildAutoRouteCleanupScript(commands []string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("set -eu\n\n")
	b.WriteString("# Generated by Xray auto_route at ")
	b.WriteString(time.Now().Format(time.RFC3339))
	b.WriteString(".\n")
	b.WriteString("# Run with root privileges only after the Xray instance that created it has exited.\n\n")
	for _, command := range commands {
		b.WriteString(command)
		if !strings.HasSuffix(command, "\n") {
			b.WriteByte('\n')
		}
	}
	b.WriteString("\nrm -f \"$0\"\n")
	return b.String()
}

func listAutoRouteCleanupScripts() []string {
	var scripts []string
	for _, dir := range autoRouteCleanupDirs() {
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, entry := range entries {
			name := entry.Name()
			if !entry.Type().IsRegular() || !strings.HasPrefix(name, autoRouteCleanupScriptPrefix) || !strings.HasSuffix(name, autoRouteCleanupScriptSuffix) {
				continue
			}
			scripts = append(scripts, filepath.Join(dir, name))
		}
	}
	return scripts
}

func autoRouteCleanupDirs() []string {
	dirs := []string{"/run/xray/auto-route", filepath.Join(os.TempDir(), "xray-auto-route")}
	if dirs[0] == dirs[1] {
		return dirs[:1]
	}
	return dirs
}

func autoRouteCleanupScriptName(tunName string) string {
	return fmt.Sprintf("%s%d-%d-%s%s", autoRouteCleanupScriptPrefix, os.Getpid(), time.Now().UnixNano(), sanitizeFilePart(tunName), autoRouteCleanupScriptSuffix)
}

func autoRouteCleanupCommand(path string) string {
	return "sudo sh " + shellQuote(path)
}

func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'"
}

func sanitizeFilePart(s string) string {
	if s == "" {
		return "tun"
	}
	var b strings.Builder
	for i := 0; i < len(s) && b.Len() < 80; i++ {
		c := s[i]
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '.' || c == '_' || c == '-' {
			b.WriteByte(c)
		} else {
			b.WriteByte('-')
		}
	}
	if b.Len() == 0 {
		return "tun"
	}
	return b.String()
}
